#ifndef STD_DEFS_H
#define	STD_DEFS_H

#define PACKET_HEADER_SIZE 12
#define PACKET_TYPE_NORMAL 0x8000
#define PACKET_TYPE_COMPRESSED 0x4000
#define PACKET_START_BIT 0xFF

#define BUFFER_DEFALT_MAX_LENGTH 4096

#define CHAR_SLOT_LENGTH 5

#endif